/*
 * File: app/view/MyContainer.js
 *
 * This file was generated by Sencha Architect version 2.2.2.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.2.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MyApp.view.MyContainer', {
    extend: 'Ext.Container',

    config: {
        items: [
            {
                xtype: 'titlebar',
                docked: 'top',
                title: 'Camara App',
                layout: {
                    align: 'center',
                    type: 'hbox'
                },
                items: [
                    {
                        xtype: 'button',
                        itemId: 'mybutton1',
                        text: 'Take!',
                        listeners: [
                            {
                                fn: function(component, eOpts) {
                                    alert("1.2");
                                },
                                event: 'initialize'
                            }
                        ]
                    }
                ]
            }
        ],
        listeners: [
            {
                fn: 'onMybutton1Tap',
                event: 'tap',
                delegate: '#mybutton1'
            }
        ]
    },

    onMybutton1Tap: function(button, e, eOpts) {
        alert("1.2");

        var c = new Ext.device.Camera();

        c.capture({
            success: function(image){
                alert("success!");
                imageView.setSrc(image);
            },
            failure: function(){
                alert("failure");
            },
            quality: 75,
            width: 300,
            height: 300,
            destination: 'data'
        });

    }

});