/*
 * File: app/view/MyContainer.js
 *
 * This file was generated by Sencha Architect version 2.2.2.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.2.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MyApp.view.MyContainer', {
    extend: 'Ext.Container',

    config: {
        items: [
            {
                xtype: 'titlebar',
                docked: 'top',
                title: 'Camara App',
                layout: {
                    align: 'center',
                    type: 'hbox'
                },
                items: [
                    {
                        xtype: 'segmentedbutton',
                        align: 'right',
                        items: [
                            {
                                xtype: 'button',
                                itemId: 'mybutton',
                                text: 'Tomar'
                            },
                            {
                                xtype: 'button',
                                text: 'Ver'
                            }
                        ]
                    }
                ]
            }
        ],
        listeners: [
            {
                fn: 'onMybuttonTap',
                event: 'tap',
                delegate: '#mybutton'
            }
        ]
    },

    onMybuttonTap: function(button, e, eOpts) {
        alert("listo");

        Ext.device.Camera.capture({
            success: function(image){
                imageView.setSrc(image);
            },
            quality: 75,
            source: 'camera',
            destination:'data',
            encoding: 'png'
        });

        alert("fak!");
    }

});